title: Gramantin
author: Ekrem Karaca
baseurl: ""
url: https://gramantin.netlify.com # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  To be updated.
header_text: Header text
header_feature_image: ""
footer_text: Footer text
permalink: /:year/:month/:title

# Pagination
paginate: 10
paginate_path: "page:num"

# Build settings
theme: type-on-strap
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-compose]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
